<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>NMX.EzChess.Library</Title>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
    <AnalysisLevel>none</AnalysisLevel>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>

</Project>
