<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <PublishAot>False</PublishAot>
    <Title>Ez Chess Console</Title>
    <Version>0.1.0</Version>
    <Authors>AnimaxNeil</Authors>
    <Company>New Media XP</Company>
    <Copyright>New Media XP</Copyright>
    <PublishTrimmed>True</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NMX.EzChess.Library\NMX.EzChess.Library.csproj" />
  </ItemGroup>

</Project>
