<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <PublishAot>True</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="NMX.EzChess.Library">
      <HintPath>..\NMX.EzChess.Library\bin\Debug\netstandard2.1\NMX.EzChess.Library.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
